import { StyleSheet } from "react-native";

/** Shared visual language for the focused, five-screen driver workflow. */
export const colors = {
  bg: "#f8fafc",
  panel: "#ffffff",
  panelSubtle: "#f1f5f9",
  border: "#e2e8f0",
  borderStrong: "#cbd5e1",
  ink: "#1e293b",
  inkMuted: "#475569",
  accent: "#2563eb",
  accentSoft: "#eff6ff",
  signal: "#ea580c",
  danger: "#b91c1c",
  dangerSoft: "#fef2f2",
  ok: "#047857",
  okSoft: "#ecfdf5",
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.bg },
  content: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 16, paddingBottom: 32, gap: 16 },
  authContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingVertical: 32,
    gap: 10,
  },
  panel: {
    backgroundColor: colors.panel,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 16,
    padding: 18,
    gap: 10,
    shadowColor: "#0f172a",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  panelPressed: { backgroundColor: colors.panelSubtle, borderColor: colors.borderStrong },
  h1: { fontSize: 26, lineHeight: 32, fontWeight: "700", letterSpacing: -0.4, color: colors.ink },
  h2: { fontSize: 16, lineHeight: 22, fontWeight: "600", color: colors.ink },
  body: { fontSize: 15, lineHeight: 22, color: colors.ink },
  muted: { fontSize: 14, lineHeight: 20, color: colors.inkMuted },
  eyebrow: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: colors.accent,
  },
  error: {
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#fecaca",
    borderRadius: 10,
    backgroundColor: colors.dangerSoft,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    lineHeight: 20,
    color: colors.danger,
  },
  success: {
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#a7f3d0",
    borderRadius: 10,
    backgroundColor: colors.okSoft,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    lineHeight: 20,
    color: colors.ok,
  },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 11,
    backgroundColor: colors.panel,
    fontSize: 16,
    color: colors.ink,
  },
  button: {
    minHeight: 48,
    backgroundColor: colors.accent,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonSecondary: {
    minHeight: 48,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonPressed: { opacity: 0.82 },
  buttonSecondaryPressed: { backgroundColor: colors.panelSubtle },
  buttonDisabled: { opacity: 0.5 },
  buttonText: { color: "#ffffff", fontWeight: "700", fontSize: 15 },
  buttonSecondaryText: { color: colors.ink, fontWeight: "600", fontSize: 15 },
  row: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  badge: {
    minHeight: 28,
    alignSelf: "flex-start",
    justifyContent: "center",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: colors.panelSubtle,
    borderWidth: 1,
    borderColor: colors.border,
  },
  badgeSelected: { borderColor: colors.accent, backgroundColor: colors.accentSoft },
  badgeText: { fontSize: 12, lineHeight: 16, color: colors.inkMuted, fontWeight: "600" },
  link: {
    minHeight: 44,
    justifyContent: "center",
    color: colors.accent,
    fontSize: 14,
    fontWeight: "600",
  },
});
