import type { AvaalCategory } from "./snapshot";
import type { AvaalPageConfig, AvaalTablePageConfig } from "./ui-traversal";

const BASE_URL = "https://avaalaem.com:8088";

export interface AvaalNotApplicablePageConfig {
  category: AvaalCategory;
  route: string;
  notApplicable: true;
  reason: string;
}

export type AvaalPageManifest = AvaalPageConfig | AvaalNotApplicablePageConfig;

const pagination = (
  tableId: string,
): NonNullable<AvaalTablePageConfig["pagination"]> => ({
  nextSelector: `#${tableId}_next`,
  nextLabel: "→",
  activePageSelector: `#${tableId}_paginate .paginate_button.current`,
});

export const AVAAL_PAGE_CONFIGS = {
  company: {
    category: "company",
    kind: "singleton",
    baseUrl: BASE_URL,
    route: "/Masters/Company/Company",
    sourceId: "pftrans-company",
    detail: {
      rootSelector: "#divCompanyForm",
      fieldAliases: {
        txtCompanyName: "Company Name",
        txtScacCode: "SCAC Code",
        txtCanadianCarrierCode: "Canadian Carrier Code",
        txtFC: "Filer Code",
        chkACI: "Include PARS in ACI Cargo Numbers",
        chkSDS: "Use Simple Driver Sheet",
        txtAddress: "Address",
        txtCity: "City",
        ddlCountryCom: "Country",
        ddlState: "Province/State",
        txtZip: "Postal/Zip Code",
        txtPhone: "Phone",
        txtFax: "Fax",
        txtCellPhone: "Cell Phone",
        ddlTimeZone: "Time Zone",
        chkSAA: "Billing Same As Above",
        txtBillingAddress: "Billing Address",
        txtBillingCity: "Billing City",
        ddlBillingCountryCom: "Billing Country",
        ddlBillingProvince: "Billing Province/State",
        txtBillingZip: "Billing Postal/Zip Code",
        ddlPackageCom: "Package",
        ddlCCTypeCom: "Credit Card Type",
        txtCcexpiry: "Credit Card Expiry",
        txtCcowner: "Cardholder Name",
      },
    },
  },
  users: {
    category: "users",
    kind: "table",
    baseUrl: BASE_URL,
    route: "/Masters/User/Users",
    tableSelector: "#userproList",
    sourceIdColumn: "Login Name",
    detail: {
      linkSelector: "a[id^='aUsers']",
      rootSelector: "#divUserProForm",
      control: "Edit",
      fieldAliases: {
        ddlTitleUsr: "Title",
        txtFNameUsr: "First Name",
        txtMNameUsr: "Middle Name",
        txtLNameUsr: "Last Name",
        txtEmailUsr: "Email",
        txtPhoneUsr: "Phone",
        txtExtensionUsr: "Phone Extension",
        txtCellCAUsr: "Cell Phone",
        txtLoginNameUsr: "Login Name",
        chkIsAdminUsr: "Is Admin",
      },
    },
    displayedTotalSelector: "#userproList_info",
    pagination: pagination("userproList"),
  },
  email_preferences: {
    category: "email_preferences",
    kind: "singleton",
    baseUrl: BASE_URL,
    route: "/Masters/EmailPreferences/EmailPreferences",
    sourceId: "pftrans-email-preferences",
    detail: {
      rootSelector: "#divEmailPreferencesForm",
      fieldAliases: {
        ChkIsEmailNotifyEP: "Email Notification Active",
        txtEmailEP1: "Email 1",
        txtEmailEP2: "Email 2",
        txtEmailEP3: "Email 3",
        txtEmailEP4: "Email 4",
        txtEmailEP5: "Email 5",
        ChkEmailToDispatchEP: "Email To Dispatch",
        ChkEmailToDriverEP: "Email To Assigned Driver",
        ChkEmailWhenAcceptedEP: "Driver Sheet When Accepted",
        ChkEmailWhenEntryNumbersEP: "Driver Sheet When Entry Numbers Complete",
      },
    },
  },
  drivers: {
    category: "drivers",
    kind: "table",
    baseUrl: BASE_URL,
    route: "/Masters/Driver/Driver",
    tableSelector: "#driverList",
    sourceIdColumn: "Driver Name",
    detail: {
      linkSelector: "a[id^='aDRVId']",
      rootSelector: "#divDriverForm",
      control: "Edit",
      fieldAliases: {
        ddlGender: "Gender",
        txtFName: "First Name",
        txtMName: "Middle Name",
        txtLName: "Last Name",
        txtDOB: "Date of Birth",
        ddlCitizenship: "Citizenship/Nationality",
        txtPhone: "Phone",
        txtCellCA: "Canada Cell Phone",
        txtCellUSA: "USA Cell Phone",
        txtEmail: "Email",
        chkIsSendSMS: "Send Entry Number SMS",
        txtAddressOne: "Address Line 1",
        ddlCountryAddress: "Address Country",
        ddlStateAddress: "Address Province/State",
        txtCity: "City",
        txtZip: "Postal/Zip Code",
        txtLicenseNum: "Driver License",
        ddlCountryLicense: "License Country",
        ddlStateLicense: "Licensed Province/State",
        ddlHazmatEndorsement: "HAZ-MAT Endorsements",
        txtEndorsementNum: "Endorsement Number",
        ddlDocumentType: "Travel Document Type",
        txtDocumentNumber: "Travel Document Number",
        ddlCountryDocument: "Travel Document Country",
      },
    },
    displayedTotalSelector: "#driverList_info",
    pagination: pagination("driverList"),
  },
  trucks: {
    category: "trucks",
    kind: "table",
    baseUrl: BASE_URL,
    route: "/Masters/Truck/Truck",
    tableSelector: "#truckList",
    sourceIdColumn: "Truck Number",
    detail: {
      linkSelector: "a[id^='aTRKId']",
      rootSelector: "#divTruckForm",
      control: "Edit",
      fieldAliases: {
        txtTruckNumber: "Truck Number",
        ddlVehicleType: "Vehicle Type",
        txtVINNumber: "VIN Number",
        txtDOTNumber: "DOT Number",
        txtTransponderId: "Transponder ID",
        chkTHM: "Transports Hazardous Materials",
        txtInsuranceCmpName: "Insurance Company Name",
        txtPlcNumber: "Insurance Policy Number",
        txtPlcAmount: "Insurance Policy Amount",
        txtPlcIssueYear: "Insurance Issue Year",
        txtLPNumber: "License Plate Number",
        ddlLPCountry: "License Plate Country",
        ddlLPState: "License Plate Province/State",
      },
    },
    displayedTotalSelector: "#truckList_info",
    pagination: pagination("truckList"),
  },
  trailers: {
    category: "trailers",
    kind: "table",
    baseUrl: BASE_URL,
    route: "/Masters/Trailer/Trailer",
    tableSelector: "#tblTrailerList",
    sourceIdColumn: "Trailer Number",
    detail: {
      linkSelector: "a[id^='aTRLId']",
      rootSelector: "#divTrailerForm",
      control: "Edit",
      fieldAliases: {
        ddlTrailerType: "Trailer Type",
        txtTrailerNumber: "Trailer Number",
        txtLPNumber: "License Plate Number",
        ddlLPCountry: "License Plate Country",
        ddlLPState: "License Plate Province/State",
      },
    },
    displayedTotalSelector: "#tblTrailerList_info",
    pagination: pagination("tblTrailerList"),
  },
  shippers: {
    category: "shippers",
    kind: "table",
    baseUrl: BASE_URL,
    route: "/Masters/Location/Shipper",
    tableSelector: "#tblLocationList",
    sourceIdColumn: "Name",
    detail: {
      linkSelector: "a[id^='aLOCId']",
      rootSelector: "#divLocationForm",
      control: "Edit",
      fieldAliases: {
        txtName: "Name",
        txtAddress: "Address",
        ddlCountry: "Country",
        ddlState: "Province/State",
        txtCity: "City",
        txtZip: "Postal/Zip Code",
        txtContact: "Contact",
        txtPhone: "Phone",
        txtEmail: "Email",
        ddlType: "Type",
      },
    },
    displayedTotalSelector: "#tblLocationList_info",
    pagination: pagination("tblLocationList"),
  },
  consignees: {
    category: "consignees",
    kind: "table",
    baseUrl: BASE_URL,
    route: "/Masters/Location/Consignee",
    tableSelector: "#tblLocationList",
    sourceIdColumn: "Name",
    detail: {
      linkSelector: "a[id^='aLOCId']",
      rootSelector: "#divLocationForm",
      control: "Edit",
      fieldAliases: {
        txtName: "Name",
        txtAddress: "Address",
        ddlCountry: "Country",
        ddlState: "Province/State",
        txtCity: "City",
        txtZip: "Postal/Zip Code",
        txtContact: "Contact",
        txtPhone: "Phone",
        txtEmail: "Email",
        ddlType: "Type",
      },
    },
    displayedTotalSelector: "#tblLocationList_info",
    pagination: pagination("tblLocationList"),
  },
  ace_manifests: {
    category: "ace_manifests",
    kind: "table",
    baseUrl: BASE_URL,
    route: "/ACE/EManifest/Manifest",
    tableSelector: "#manifestList",
    sourceIdColumn: "Trip Number",
    detail: {
      linkSelector: "a[id^='aMFTId']",
      rootSelector: "#divManifestForm",
      control: "View",
      fieldAliases: {
        ddlSCACMNF: "SCAC",
        txtTripNoMNF: "Trip Number",
        txtArrivalPortNameMNF: "Port Name",
        txtArrivalPortMNF: "Port Code",
        txtArrivalDateMNF: "Arrival Date",
        txtArrivalTimeMNF: "Arrival Time",
        ddlManifestTypeMNF: "Manifest Type",
        ddlIITMNF: "IIT Type",
      },
      tableAliases: {
        tblTruckInfoMNF: "Trucks",
        tblCrewInfoMNF: "Crew",
        tblShipmentMNF: "Shipments",
        tblEquipmentMNF: "Equipment",
        tblEmptyEquipmentMNF: "Empty Equipment",
        tblSealNumberMNF: "Seals",
        tblNotificationMNF: "Event History",
      },
    },
    displayedTotalSelector: "#manifestList_info",
    pagination: pagination("manifestList"),
  },
  ace_shipments: {
    category: "ace_shipments",
    kind: "table",
    baseUrl: BASE_URL,
    route: "/ACE/Shipment/Shipment",
    tableSelector: "#tblShipmentList",
    sourceIdColumn: "SCN",
    detail: {
      linkSelector: "a[id^='aSMTId']",
      rootSelector: "#divShipmentForm",
      control: "View",
      fieldAliases: {
        ddlShipmentTypeSMT: "Shipment Type",
        ddlSCACCodeSMT: "SCAC",
        txtSCNoSMT: "Shipment Control Number",
        ddlCountrySMT: "Country",
        ddlStateSMT: "Province/State",
        txtTripNumberSMT: "Attached Trip Number",
        ddlShipperSMT: "Selected Shipper",
        txtShipperNameSMT: "Shipper Name",
        txtShipperAddressSMT: "Shipper Address",
        ddlShipperCountrySMT: "Shipper Country",
        ddlShipperStateSMT: "Shipper Province/State",
        txtShipperCitySMT: "Shipper City",
        txtShipperZipSMT: "Shipper Postal/Zip Code",
        txtShipperPhoneSMT: "Shipper Phone",
        txtShipperEmailSMT: "Shipper Email",
        ddlConsigneeSMT: "Selected Consignee",
        txtConsigneeNameSMT: "Consignee Name",
        txtConsigneeAddressSMT: "Consignee Address",
        ddlConsigneeCountrySMT: "Consignee Country",
        ddlConsigneeStateSMT: "Consignee Province/State",
        txtConsigneeCitySMT: "Consignee City",
        txtConsigneeZipSMT: "Consignee Postal/Zip Code",
        txtConsigneePhoneSMT: "Consignee Phone",
        txtConsigneeEmailSMT: "Consignee Email",
      },
      tableAliases: { tblCommoditySMT: "Commodities" },
    },
    displayedTotalSelector: "#tblShipmentList_info",
    pagination: pagination("tblShipmentList"),
  },
  aci_trips: {
    category: "aci_trips",
    kind: "table",
    baseUrl: BASE_URL,
    route: "/ACI/Trip/Trip",
    tableSelector: "#TripList",
    sourceIdColumn: "Trip #/CRN",
    detail: {
      linkSelector: "a[id^='aTPId']",
      rootSelector: "#divTripForm",
      control: "View",
      fieldAliases: {
        ddlCarrireCodeTrp: "Carrier Code",
        txtTripNoTrp: "Trip Number",
        txtArrivalPortTrp: "Arrival Port",
        txtArrivalDateTrp: "Arrival Date",
        txtArrivalTimeTrp: "Arrival Time",
        chkEmptyTripTrp: "Empty Trip",
        chkLVSTrp: "LVS",
        chkIITTrp: "IIT",
        chkPostalTrp: "Postal",
        chkflyTrkTrp: "Flying Trucks",
        chkinTransit: "In Transit",
        ddlAmendmentCode: "Amendment Code",
      },
      tableAliases: {
        tblTruckInfoTrp: "Trucks",
        tblCrewInfoTrp: "Crew",
        tblCargoTrp: "Cargos",
        tblEquipmentTrp: "Equipment",
        tblSealNumberTrp: "Seals",
        tblEmptyEquipmentTrp: "Empty Equipment",
        tblNotificationTrp: "Event History",
      },
    },
    displayedTotalSelector: "#TripList_info",
    pagination: pagination("TripList"),
  },
  aci_cargos: {
    category: "aci_cargos",
    kind: "table",
    baseUrl: BASE_URL,
    route: "/ACI/Cargo/Cargo",
    tableSelector: "#tblCargoList",
    sourceIdColumn: "CCC/Cargo #",
    detail: {
      linkSelector: "a[id^='aCRGId']",
      rootSelector: "#divCargoForm",
      control: "View",
      fieldAliases: {
        ddlCarrierCodeCRG: "Carrier Code",
        txtPARSCRG: "PARS/Cargo Number",
        chkIsStartPARS: "Starts With PARS",
        txtPOANameCRG: "Port of Arrival",
        txtArrivalDateCRG: "Arrival Date",
        txtArrivalTimeCRG: "Arrival Time",
        ddlCargoTypeCRG: "Cargo Type",
        chkIsCldtCargo: "Consolidated Cargo",
        txtTripNo: "Attached Trip",
        txtCargoStatus: "Status",
        ddlShipperCRG: "Selected Shipper",
        txtShipperNameCRG: "Shipper Name",
        txtShipperAddressCRG: "Shipper Address",
        ddlShipperCountryCRG: "Shipper Country",
        ddlShipperStateCRG: "Shipper Province/State",
        txtShipperCityCRG: "Shipper City",
        txtShipperZipCRG: "Shipper Postal/Zip Code",
        txtShipperContactCRG: "Shipper Contact",
        txtShipperPhoneCRG: "Shipper Phone",
        ddlConsigneeCRG: "Selected Consignee",
        txtConsigneeNameCRG: "Consignee Name",
        txtConsigneeAddressCRG: "Consignee Address",
        ddlConsigneeCountryCRG: "Consignee Country",
        ddlConsigneeStateCRG: "Consignee Province/State",
        txtConsigneeCityCRG: "Consignee City",
        txtConsigneeZipCRG: "Consignee Postal/Zip Code",
        txtConsigneeContactCRG: "Consignee Contact",
        txtConsigneePhoneCRG: "Consignee Phone",
        ddlLoadingCountryCRG: "Loading Country",
        ddlLoadingStateCRG: "Loading Province/State",
        txtLoadingCityCRG: "Loading City",
        txtPODCRG: "Port of Destination",
        txtCBSASubLocationCRG: "CBSA Sub-location",
      },
      tableAliases: {
        tblCommodityCRG: "Commodities",
        tblDAddressCRG: "Delivery Addresses",
        tblEventsCRG: "Event History",
      },
    },
    displayedTotalSelector: "#tblCargoList_info",
    pagination: pagination("tblCargoList"),
  },
  external_shipments: {
    category: "external_shipments",
    kind: "table",
    baseUrl: BASE_URL,
    route: "/ACE/ExternalShipment/ExternalShipment",
    tableSelector: "#tblExternalShipmentList",
    sourceIdColumn: "ShipmentControl",
    displayedTotalSelector: "#tblExternalShipmentList_info",
    pagination: pagination("tblExternalShipmentList"),
  },
  tcp: {
    category: "tcp",
    route: "/ACI/Tcp/Tcp",
    notApplicable: true,
    reason: "No TCP control or route is exposed in the authenticated pftrans navigation.",
  },
  pars_rns: {
    category: "pars_rns",
    route: "/ACI/ParsRns/ParsRns",
    notApplicable: true,
    reason: "Authenticated PARS RNS navigation returns to Login instead of rendering a tenant table.",
  },
  inbond: {
    category: "inbond",
    route: "/Masters/InBondMonitor/InBondMonitor",
    notApplicable: true,
    reason: "No In-Bond Monitor control or route is exposed in the authenticated pftrans navigation.",
  },
} satisfies Record<AvaalCategory, AvaalPageManifest>;

export const AVAAL_EXTRACTION_ORDER = [
  "company",
  "email_preferences",
  "users",
  "drivers",
  "trucks",
  "trailers",
  "shippers",
  "consignees",
  "ace_manifests",
  "ace_shipments",
  "external_shipments",
  "aci_trips",
  "aci_cargos",
  "tcp",
  "pars_rns",
  "inbond",
] as const satisfies readonly AvaalCategory[];
